### ISSUE TITLE
gwt compile problem with 1.4.4-SNAPSHOT

### ISSUE THREAD

**Issue by biancashouse** [ArcBees/gwtquery#344]
gwt 2.7.0
This selector interface compiles o.k. with previous gwt-query versions...

package au.com.mobilett.gwt.gamehub.client.app.mobilett;
import com.google.gwt.query.client.GQuery;
import com.google.gwt.query.client.Selector;
import com.google.gwt.query.client.Selectors;

public interface I_TPD_Selectors extends Selectors {
   
  @Selector("#login-panel")
  GQuery qTheLoginPanel();
  
  @Selector("#programs-menu-div")
  GQuery qTheProgramsMenuDiv();
  
  @Selector("#programs-menu-div > div.btn-group")
  GQuery qTheProgramsMenuButtonGroup();
  
  @Selector("#topics-menu-div")
  GQuery qTheTopicsMenuDiv();
  
  @Selector("#topics-menu-div > div.btn-group")
  GQuery qTheTopicsMenuButtonGroup();
  
  @Selector("#tests-menu-div")
  GQuery qTheTestsMenuDiv();
  
  @Selector("#tests-menu-div > div.btn-group")
  GQuery qTheTestsMenuButtonGroup();
  
  @Selector("#yesno-q")
  GQuery qTheYesNoQuestionDiv();
  
  @Selector("#selection-q-div")
  GQuery qTheSelectionQuestionDiv();
  
  @Selector("#dnd-q-div")
  GQuery qTheDnDQuestionDiv();
  
  @Selector("button#imready")
  GQuery qTheImReadyButton();
  
  @Selector("#col1")
  GQuery qCol1();
  
  @Selector("#col2")
  GQuery qCol2();
  
  @Selector("#col3")
  GQuery qCol3();
  
  @Selector("div.btn-group")
  GQuery qAnyButtonGroup();
  

  @Selector("#test-progress")
  GQuery qTheTestProgress();
  
  @Selector("#group-progress")
  GQuery qTheGroupProgress();
  
  @Selector("#circle-timer-canvas")
  GQuery qTheCircleTimerCanvas();

  @Selector("#wave-canvas")
  GQuery qTheWaveTimerCanvas();

  @Selector("#gauge-canvas")
  GQuery qTheGaugeTimerCanvas();
}

the errors are...

Buildfile: /Users/ianw/my/g.appspot.club/gwt-gamehub/build+gamehub.xml
local-training-program-demo:
     [copy] Copying 1 file to /Users/ianw/my/g.appspot.club/gwt-gamehub/src/main/webapp/WEB-INF
     [copy] Copying 1 file to /Users/ianw/my/g.appspot.club/gwt-gamehub/src/main/webapp/WEB-INF
local-dev-server:
versioning.gwt.modules:
incr-properties:
[propertyfile] Updating property file: /Users/ianw/my/g.appspot.club/gwt-gamehub/version.gwt.properties
     [echo] #Build version info
     [echo] #Sat, 28 Feb 2015 11:44:11 +1100
     [echo] buildDate=2015/02/28 11\:44
     [echo] buildNum=156
     [copy] Copying 1 file to /Users/ianw/my/g.appspot.club/gwt-gamehub/src/main/java/au/com/mobilett/gwt/gamehub/client
     [echo] Replacing properties
mvn:
     [echo] maven command: clean appengine:devserver -Dmaven.offline.true -P common-gwt-module-deps
     [exec] [INFO] Scanning for projects...
     [exec] [INFO]                                                                         
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Building gwt-gamehub 1.0
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] 
     [exec] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gwt-gamehub ---
     [exec] [INFO] Deleting /Users/ianw/my/g.appspot.club/gwt-gamehub/target
     [exec] [INFO] 
     [exec] [INFO] >>> appengine-maven-plugin:1.9.17:devserver (default-cli) > package @ gwt-gamehub >>>
     [exec] [INFO] 
     [exec] [INFO] --- gwt-maven-plugin:2.7.0-rc1:css (css-generation) @ gwt-gamehub ---
     [exec] [INFO] 
     [exec] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gwt-gamehub ---
     [exec] [INFO] Using 'UTF-8' encoding to copy filtered resources.
     [exec] [INFO] Copying 186 resources
     [exec] [INFO] Copying 4 resources
     [exec] [INFO] 
     [exec] [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gwt-gamehub ---
     [exec] [INFO] Changes detected - recompiling the module!
     [exec] [INFO] Compiling 141 source files to /Users/ianw/my/g.appspot.club/gwt-gamehub/target/classes
     [exec] [INFO] 
     [exec] [INFO] --- gwt-maven-plugin:2.7.0-rc1:generateAsync (async-for-run-or-debug) @ gwt-gamehub ---
     [exec] [INFO] 
     [exec] [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gwt-gamehub ---
     [exec] [INFO] Using 'UTF-8' encoding to copy filtered resources.
     [exec] [INFO] skip non existing resourceDirectory /Users/ianw/my/g.appspot.club/gwt-gamehub/src/test/resources
     [exec] [INFO] 
     [exec] [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gwt-gamehub ---
     [exec] [INFO] No sources to compile
     [exec] [INFO] 
     [exec] [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ gwt-gamehub ---
     [exec] [INFO] No tests to run.
     [exec] [INFO] 
     [exec] [INFO] --- gwt-maven-plugin:2.7.0-rc1:compile (gwt) @ gwt-gamehub ---
     [exec] [INFO] Compiling module au.com.mobilett.gwt.gamehub.GWT_Gamehub
     [exec] [INFO]    [ERROR] An internal compiler exception occurred
     [exec] [INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:296)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1505)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:870)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1303)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1036)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:953)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
     [exec] [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
     [exec] [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
     [exec] [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
     [exec] [INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
     [exec] [INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:158)
     [exec] [INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
     [exec] [INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [exec] [INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [exec] [INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:127)
     [exec] [INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.query.client.GQuery.$(Lcom/google/gwt/dom/client/NodeList;)Lcom/google/gwt/query/client/GQuery;
     [exec] [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1715)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.access$1100(UnifyAst.java:134)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:416)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:245)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
     [exec] [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [exec] [INFO] 	... 35 more
     [exec] [INFO]       [ERROR] at I_TPD_Selectors_NativeCssToXPathImpl.java(39): GQuery.$(SelectorEngine.veryQuickId("login-panel", this.root))
     [exec] [INFO]          com.google.gwt.dev.jjs.ast.JMethodCall
     [exec] [INFO]       [ERROR] at I_TPD_Selectors_NativeCssToXPathImpl.java(39): return GQuery.$(SelectorEngine.veryQuickId("login-panel", this.root))
     [exec] [INFO]          com.google.gwt.dev.jjs.ast.JReturnStatement
     [exec] [INFO]       [ERROR] at I_TPD_Selectors_NativeCssToXPathImpl.java(38): {
     [exec] [INFO]   return GQuery.$(SelectorEngine.veryQuickId("login-panel", this.root));
     [exec] [INFO] }
     [exec] [INFO]          com.google.gwt.dev.jjs.ast.JBlock
     [exec] [INFO]       [ERROR] at I_TPD_Selectors_NativeCssToXPathImpl.java(38): {
     [exec] [INFO]   return GQuery.$(SelectorEngine.veryQuickId("login-panel", this.root));
     [exec] [INFO] }
     [exec] [INFO]          com.google.gwt.dev.jjs.ast.JMethodBody
     [exec] [INFO]       [ERROR] at I_TPD_Selectors_NativeCssToXPathImpl.java(38): public final GQuery qTheLoginPanel();
     [exec] [INFO] 
     [exec] [INFO]          com.google.gwt.dev.jjs.ast.JMethod
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD FAILURE
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time: 15.623 s
     [exec] [INFO] Finished at: 2015-02-28T11:44:28+11:00
     [exec] [INFO] Final Memory: 17M/310M
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0-rc1:compile (gwt) on project gwt-gamehub: Command [[
     [exec] [ERROR] /bin/sh -c '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/bin/java' '-Xmx2048M' '-Xms1024M' '-Xss1024k' '-XX:MaxPermSize=256M' '-classpath' '/Users/ianw/my/g.appspot.club/gwt-gamehub/target/classes:/Users/ianw/my/g.appspot.club/gwt-gamehub/src/main/java:/Users/ianw/my/m2/repository/com/googlecode/gwtquery/gwtquery/1.4.4-SNAPSHOT/gwtquery-1.4.4-SNAPSHOT.jar:/Users/ianw/my/m2/repository/com/google/gwt/gwt-elemental/2.7.0/gwt-elemental-2.7.0.jar:/Users/ianw/my/m2/repository/com/arcbees/gquery/droppable/2.0-SNAPSHOT/droppable-2.0-SNAPSHOT.jar:/Users/ianw/my/m2/repository/com/arcbees/gquery/draggable/2.0-SNAPSHOT/draggable-2.0-SNAPSHOT.jar:/Users/ianw/my/m2/repository/org/gwtbootstrap3/gwtbootstrap3/1.0-SNAPSHOT/gwtbootstrap3-1.0-SNAPSHOT.jar:/Users/ianw/my/m2/repository/org/gwtbootstrap3/gwtbootstrap3-extras/1.0-SNAPSHOT/gwtbootstrap3-extras-1.0-SNAPSHOT.jar:/Users/ianw/my/m2/repository/com/google/gwt/gwt-user/2.7.0/gwt-user-2.7.0.jar:/Users/ianw/my/m2/repository/com/google/gwt/eventbinder/eventbinder/1.0.2/eventbinder-1.0.2.jar:/Users/ianw/my/m2/repository/com/googlecode/gwtphonegap/gwtphonegap/3.5.0.0/gwtphonegap-3.5.0.0.jar:/Users/ianw/my/m2/repository/commons-io/commons-io/2.0.1/commons-io-2.0.1.jar:/Users/ianw/my/m2/repository/com/googlecode/mgwt/mgwt/2.0.0/mgwt-2.0.0.jar:/Users/ianw/my/m2/repository/com/github/nmorel/gwtjackson/gwt-jackson/0.2.1/gwt-jackson-0.2.1.jar:/Users/ianw/my/m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar:/Users/ianw/my/m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0-sources.jar:/Users/ianw/my/m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/ianw/my/m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/ianw/my/m2/repository/com/google/gwt/gwt-user/2.7.0-rc1/gwt-user-2.7.0-rc1.jar:/Users/ianw/my/m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/ianw/my/m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/ianw/my/m2/repository/com/google/gwt/gwt-dev/2.7.0-rc1/gwt-dev-2.7.0-rc1.jar:/Users/ianw/my/m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/Users/ianw/my/m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar:/Users/ianw/my/m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar:/Users/ianw/my/m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-style' 'PRETTY' '-war' '/Users/ianw/my/g.appspot.club/gwt-gamehub/src/main/webapp' '-localWorkers' '8' '-XfragmentCount' '-1' '-sourceLevel' '1.7' '-gen' '/Users/ianw/my/g.appspot.club/gwt-gamehub/target/.generated' 'au.com.mobilett.gwt.gamehub.GWT_Gamehub'
     [exec] [ERROR] ]] failed with status 1
     [exec] [ERROR] -> [Help 1]
     [exec] [ERROR] 
     [exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [exec] [ERROR] 
     [exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

BUILD FAILED
/Users/ianw/my/g.appspot.club/gwt-gamehub/build+gamehub.xml:33: The following error occurred while executing this line:
/Users/ianw/my/g.appspot.club/gwt-gamehub/build+gamehub.xml:43: The following error occurred while executing this line:
/Users/ianw/my/g.appspot.club/ant/build+mvn.xml:29: exec returned: 1

Total time: 18 seconds

**Comment by biancashouse** [comment]
BTW - the generated java that causes the error is:

package au.com.mobilett.gwt.gamehub.client.app.mobilett;

import com.google.gwt.query.client.impl.*;
import com.google.gwt.query.client.js.*;
import com.google.gwt.query.client.Selectors.*;
import com.google.gwt.query.client.*;
import com.google.gwt.core.client.*;
import com.google.gwt.dom.client.*;

public class I_TPD_Selectors_NativeCssToXPathImpl extends com.google.gwt.query.client.impl.SelectorEngine implements au.com.mobilett.gwt.gamehub.client.app.mobilett.I_TPD_Selectors {
  public final com.google.gwt.query.client.GQuery qAnyButtonGroup() {
    return GQuery.$(querySelectorAll("div.btn-group", root));
  }
  public final com.google.gwt.query.client.GQuery qCol1() {
    return GQuery.$(JsNodeArray.create(((Document)root).getElementById("col1")));
  }
  public final com.google.gwt.query.client.GQuery qCol2() {
    return GQuery.$(JsNodeArray.create(((Document)root).getElementById("col2")));
  }
  public final com.google.gwt.query.client.GQuery qCol3() {
    return GQuery.$(JsNodeArray.create(((Document)root).getElementById("col3")));
  }
  public final com.google.gwt.query.client.GQuery qTheCircleTimerCanvas() {
    return GQuery.$(veryQuickId("circle-timer-canvas", root));
  }
  public final com.google.gwt.query.client.GQuery qTheDnDQuestionDiv() {
    return GQuery.$(veryQuickId("dnd-q-div", root));
  }
  public final com.google.gwt.query.client.GQuery qTheGaugeTimerCanvas() {
    return GQuery.$(veryQuickId("gauge-canvas", root));
  }
  public final com.google.gwt.query.client.GQuery qTheGroupProgress() {
    return GQuery.$(veryQuickId("group-progress", root));
  }
  public final com.google.gwt.query.client.GQuery qTheImReadyButton() {
    return GQuery.$(querySelectorAll("button#imready", root));
  }
  public final com.google.gwt.query.client.GQuery qTheLoginPanel() {
    return GQuery.$(veryQuickId("login-panel", root));
  }
  public final com.google.gwt.query.client.GQuery qTheProgramsMenuButtonGroup() {
    return GQuery.$(querySelectorAll("#programs-menu-div > div.btn-group", root));
  }
  public final com.google.gwt.query.client.GQuery qTheProgramsMenuDiv() {
    return GQuery.$(veryQuickId("programs-menu-div", root));
  }
  public final com.google.gwt.query.client.GQuery qTheSelectionQuestionDiv() {
    return GQuery.$(veryQuickId("selection-q-div", root));
  }
  public final com.google.gwt.query.client.GQuery qTheTestProgress() {
    return GQuery.$(veryQuickId("test-progress", root));
  }
  public final com.google.gwt.query.client.GQuery qTheTestsMenuButtonGroup() {
    return GQuery.$(querySelectorAll("#tests-menu-div > div.btn-group", root));
  }
  public final com.google.gwt.query.client.GQuery qTheTestsMenuDiv() {
    return GQuery.$(veryQuickId("tests-menu-div", root));
  }
  public final com.google.gwt.query.client.GQuery qTheTopicsMenuButtonGroup() {
    return GQuery.$(querySelectorAll("#topics-menu-div > div.btn-group", root));
  }
  public final com.google.gwt.query.client.GQuery qTheTopicsMenuDiv() {
    return GQuery.$(veryQuickId("topics-menu-div", root));
  }
  public final com.google.gwt.query.client.GQuery qTheWaveTimerCanvas() {
    return GQuery.$(veryQuickId("wave-canvas", root));
  }
  public final com.google.gwt.query.client.GQuery qTheYesNoQuestionDiv() {
    return GQuery.$(veryQuickId("yesno-q", root));
  }
  public DeferredSelector[] getAllSelectors() {return ds;}
  private final DeferredSelector[] ds = new DeferredSelector[] {
    new DeferredSelector() {
      public String getSelector() { return "div.btn-group"; }
      public NodeList<Element> runSelector(Node ctx) { return qAnyButtonGroup().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#col1"; }
      public NodeList<Element> runSelector(Node ctx) { return qCol1().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#col2"; }
      public NodeList<Element> runSelector(Node ctx) { return qCol2().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#col3"; }
      public NodeList<Element> runSelector(Node ctx) { return qCol3().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#circle-timer-canvas"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheCircleTimerCanvas().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#dnd-q-div"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheDnDQuestionDiv().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#gauge-canvas"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheGaugeTimerCanvas().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#group-progress"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheGroupProgress().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "button#imready"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheImReadyButton().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#login-panel"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheLoginPanel().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#programs-menu-div > div.btn-group"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheProgramsMenuButtonGroup().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#programs-menu-div"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheProgramsMenuDiv().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#selection-q-div"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheSelectionQuestionDiv().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#test-progress"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheTestProgress().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#tests-menu-div > div.btn-group"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheTestsMenuButtonGroup().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#tests-menu-div"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheTestsMenuDiv().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#topics-menu-div > div.btn-group"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheTopicsMenuButtonGroup().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#topics-menu-div"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheTopicsMenuDiv().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#wave-canvas"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheWaveTimerCanvas().get();}
    },
    new DeferredSelector() {
      public String getSelector() { return "#yesno-q"; }
      public NodeList<Element> runSelector(Node ctx) { return qTheYesNoQuestionDiv().get();}
    },
  };
}

**Comment by biancashouse** [comment]
RED HERRING
---------------------
Looks like a corrupted artifact (the latest droppable).
I replaced:

 		<dependency>
			<groupId>com.arcbees.gquery</groupId>
			<artifactId>droppable</artifactId>
			<version>2.0-SNAPSHOT</version>
		</dependency>

with

                <dependency>
			<groupId>com.googlecode.gwtquery.plugins</groupId>
			<artifactId>enhance-plugin</artifactId>
			<scope>provided</scope>
			<version>${gwt.query.enhance.version}</version>
		</dependency>

and compile works again...

**Comment by biancashouse** [comment]
Found that I was using a old snapshot.
Now using 2.0.0 in my build, and there's a later issue arising from this...
CLOSED
